[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rebirth_program = "42we4cDKuoWk3bA9ApqP6b3i1UppF3uXtaQkHf2PjgLV"

[programs.devnet]
rebirth_program = "42we4cDKuoWk3bA9ApqP6b3i1UppF3uXtaQkHf2PjgLV"

[provider]
cluster = "devnet"
wallet = "/home/devair/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
